
(function(){var canvas=document.getElementById('Canvas'),ctx=canvas.getContext('2d');canvas.width=320;canvas.height=430;var touchDevice=false;var instructionScreen=false;var splashScreen=true;var maxBet=500;var draw={clear:function(){ctx.clearRect(0,0,canvas.width,canvas.height);},line:function(x1,y1,x2,y2,linewidth,col){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.closePath();ctx.lineWidth=linewidth;ctx.strokeStyle=col;ctx.stroke();},rect:function(x,y,w,h,col){ctx.fillStyle=col;ctx.fillRect(x,y,w,h);},circle:function(x,y,radius,col){ctx.fillStyle=col;ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2,true);ctx.closePath();ctx.fill();},circleoutline:function(x,y,radius,col,linewidth){ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2,true);ctx.closePath();ctx.lineWidth=linewidth;ctx.strokeStyle=col;ctx.stroke();},text:function(str,x,y,size,col){ctx.font='bold '+size+'px '+'verdana';ctx.fillStyle=col;ctx.fillText(str,x,y);}};splashImage=new Image();splashImage.src="images/splash-page.png";instructionsImage=new Image();instructionsImage.src="images/instructions-page.png";coinImage=new Image();coinImage.src="images/gratiicoin25b.png";gImage=new Image();gImage.src="images/g.png";gPlusImage=new Image();gPlusImage.src="images/g-plus.png";gMinusImage=new Image();gMinusImage.src="images/g-minus.png";arrowImage=new Image();arrowImage.src="images/arrow-split.png";buttonBackImage=new Image();buttonBackImage.src="images/button3.png";chipsImage=new Image();chipsImage.src="images/chips.png";var gratiiWinnings=0;function getUserGratii(){$.get('../../users/php/getUserGratii.php',function(data){if(data!=null){myGratii=data;}});}
function postBetGratii(){var online=navigator.onLine;if(online==false){alert("Oh no! You lost internet connection.");window.location="../../users/html/arcade.html";return;}
$.post('../api/gameOver.php',{score:(betTotal*-1)},"json");}
function postGratiiWon(){var online=navigator.onLine;if(online==false){alert("Oh no! You lost internet connection.");window.location="../../users/html/arcade.html";return;}
$.post('../api/gameOver.php',{score:gratiiWinnings},"json");}
function Card(num,suit){this.num=num;this.suit=suit;this.image=new Image();this.image.src="images/"+this.num+"_"+this.suit+".png";}
function CardBack(){this.image=new Image();this.image.src="images/cardback.png";}
function Deck(){this.cards=new Array(52);this.next_card=0;for(i=1;i<14;i++){this.cards[i-1]=new Card(i,"c");this.cards[i+12]=new Card(i,"h");this.cards[i+25]=new Card(i,"s");this.cards[i+38]=new Card(i,"d");}
this.shuffle=function(){for(i=1;i<1000;i++){card1=Math.floor(52*Math.random());card2=Math.floor(52*Math.random());temp=this.cards[card2];this.cards[card2]=this.cards[card1];this.cards[card1]=temp;}
this.next_card=0;};this.dealCard=function(){return this.cards[this.next_card++];};}
function addBet(amt){player_split_hand=new Array();if(myGratii>=amt){myGratii-=amt;betTotal+=amt;previousBet+=amt;if(betTotal>maxBet){alert("Max bet is "+maxBet+" Gratii");betTotal-=amt;myGratii+=amt;previousBet=betTotal;}}else{alert("Not enough Gratii bro");}}
function clearBet(amt){myGratii+=amt;betTotal=0;}
function nextBet(){previousBet=betTotal;betTotal=0;}
function setPreviousBet(){previousBet=betTotal;}
function newGame(){if(gameState=='deal'){if(deck.next_card>39){deck.shuffle();}
dealer_hand=new Array();player_hand=new Array();player_split_hand=new Array();dealer_hand[0]=deck.dealCard();dealer_hand[1]=deck.dealCard();player_hand[0]=deck.dealCard();player_hand[1]=deck.dealCard();}}
function checkIfBlackjack(){playerHandScore=score(player_hand);if(playerHandScore==21&&player_hand.length==2&&gameState=='play'){stand();return;}}
function score(hand){if(hand!=null){var total=0;var soft=0;var pips=0;for(i=0;i<hand.length;i++){pips=hand[i].num;if(pips==1){soft=soft+1;total=total+11;}else{if(pips==11||pips==12||pips==13){total=total+10;}else{total=total+pips;}}}
while(soft>0&&total>21){total=total-10;soft=soft-1;}
return total;}}
function scoreCard(card){var total=0;var soft=0;var pips=0;pips=card.num;if(pips==1){soft=soft+1;total=total+11;}else{if(pips==11||pips==12||pips==13){total=total+10;}else{total=total+pips;}}
while(soft>0&&total>21){total=total-10;soft=soft-1;}
return total;}
function winner(){if(gameState!='split'){var player_total=score(player_hand);var dealer_total=score(dealer_hand);if(player_total==21&&player_hand.length==2){return'playerblackjack';}
if(player_total==21&&player_hand.length==2&&dealer_total==21){return'tie';}
if(player_total>21){return'dealer';}else if(dealer_total>21){return'player';}else if(player_total==dealer_total){return'tie';}else if(player_total>dealer_total){return'player';}else{return'dealer';}}
else if(gameState=='split'&&splitCurrentHand==1){var player_total=score(player_hand);var dealer_total=score(dealer_hand);if(player_total==21&&player_hand.length==2){return'playerblackjack';}
if(player_total==21&&player_hand.length==2&&dealer_total==21){return'tie';}
if(player_total>21){return'dealer';}else if(dealer_total>21){return'player';}else if(player_total==dealer_total){return'tie';}else if(player_total>dealer_total){return'player';}else{return'dealer';}}else if(gameState=='split'&&splitCurrentHand==2){var player_split_total=score(player_split_hand);var dealer_total=score(dealer_hand);if(player_split_total==21&&player_split_hand.length==2){return'playerblackjack';}
if(player_split_total==21&&player_split_hand.length==2&&dealer_total==21){return'tie';}
if(player_split_total>21){return'dealer';}else if(dealer_total>21){return'player';}else if(player_split_total==dealer_total){return'tie';}else if(player_split_total>dealer_total){return'player';}else{return'dealer';}}}
function payWinnings(winstate){if(gameState!='split'){if(winstate=="dealer"){totalWon-=betTotal;gameState='game_over';winState="none";gratiiWinnings=0;}
if(winstate=="player"){gratiiWinnings+=betTotal*2;myGratii+=betTotal*2;totalWon+=betTotal;gameState='game_over';winState="none";}
if(winstate=="tie"){gratiiWinnings+=betTotal;myGratii+=betTotal;gameState='game_over';winState="none";}
if(winstate=="playerblackjack"){gratiiWinnings+=Math.round(((3/2)*betTotal)+betTotal);myGratii+=Math.round(((3/2)*betTotal)+betTotal);totalWon+=Math.round((3/2)*betTotal);gameState='game_over';winState="none";}}else if(gameState=='split'&&splitCurrentHand==1){temporaryWon=0;if(winstate=="dealer"){temporaryWon-=Math.round(betTotal/2);totalWon-=betTotal/2;splitCurrentHand=2;gratiiWinnings=0;}
if(winstate=="player"){totalWon+=betTotal;temporaryWon+=Math.round(betTotal);splitCurrentHand=2;}
if(winstate=="tie"){temporaryWon+=Math.round(betTotal/2);splitCurrentHand=2;}
if(winstate=="playerblackjack"){totalWon+=betTotal/2;temporaryWon+=Math.round(betTotal);splitCurrentHand=2;}}else if(gameState=='split'&&splitCurrentHand==2){if(temporaryWon>0){gratiiWinnings+=temporaryWon;myGratii+=temporaryWon;}else if(temporaryWon<0){}else if(temporaryWon==0){}
if(winstate=="dealer"){totalWon-=Math.round(betTotal/2);gameState='split_game_over';winState="none";gratiiWinnings=0;}
if(winstate=="player"){gratiiWinnings+=Math.round(betTotal);myGratii+=Math.round(betTotal);totalWon+=Math.round(betTotal/2);gameState='split_game_over';winState="none";}
if(winstate=="tie"){gratiiWinnings+=Math.round(betTotal/2);myGratii+=Math.round(betTotal/2);gameState='split_game_over';winState="none";}
if(winstate=="playerblackjack"){gratiiWinnings+=Math.round(betTotal);myGratii+=Math.round(betTotal);totalWon+=Math.round(betTotal/2);gameState='split_game_over';winState="none";}}
postGratiiWon(gratiiWinnings);gratiiWinnings=0;}
function deal(){gameState='deal';winnerState='none';gratiiWinnings=0;cardShowState=true;if(cardShowState==true&&betTotal==0){cardShowState=false;gameState='bet';winnerState='none';alert("You must place a bet to play at this table bro");}else if(cardShowState==true&&betTotal>=1){postBetGratii();}}
function hit(){if(gameState!='split'){var new_card=0;if(gameState=='game_over'){alert("Game over.  Click the Deal button to start a new hand.");}else{new_card=player_hand.length;player_hand[new_card]=deck.dealCard();playerHandScore=score(player_hand);if(DoublingUp==true){DoublingUp=false;if(playerHandScore>21){winnerState=winner();payWinnings(winnerState);return;}else{stand();return;}}
if(playerHandScore>21){winnerState=winner();payWinnings(winnerState);}else if(playerHandScore==21){stand();}else{}}}else if(gameState=='split'&&splitCurrentHand==1){var new_card=0;if(gameState=='game_over'){alert("Game over.  Click the Deal button to start a new hand.");}else{new_card=player_hand.length;player_hand[new_card]=deck.dealCard();playerHandScore=score(player_hand);if(playerHandScore>21){winnerState=winner();payWinnings(winnerState);}else if(playerHandScore==21){stand();}else{}}}else if(gameState=='split'&&splitCurrentHand==2){var new_card=0;if(gameState=='game_over'){alert("Game over.  Click the Deal button to start a new hand.");}else{new_card=player_split_hand.length;player_split_hand[new_card]=deck.dealCard();playerSplitHandScore=score(player_split_hand);if(playerSplitHandScore>21){winnerState=winner();payWinnings(winnerState);}else if(playerSplitHandScore==21){stand();}else{}}}}
function stand(){var new_card=0;if(gameState=='game_over'){}else{while(score(dealer_hand)<17){new_card=dealer_hand.length;dealer_hand[new_card]=deck.dealCard();}
dealerHandScore=score(dealer_hand);winnerState=winner();payWinnings(winnerState);return;}}
function reBet(){player_split_hand=new Array();if(myGratii>=previousBet){myGratii-=previousBet;betTotal=previousBet;deal();}else{alert("Not enough gratii bro");}}
var DoublingUp=false;function doubleUp(){if(gameState!='split'){if(player_hand.length==2){if(myGratii>=betTotal){postBetGratii();myGratii-=betTotal;betTotal*=2;DoublingUp=true;hit();}else{alert("Not enough gratii bro");}}else{alert("You have too many cards to double down.");}}else if(gameState=='split'){}}
function split(){if(player_hand[0].num==player_hand[1].num){if(myGratii>=betTotal){postBetGratii();myGratii-=betTotal
betTotal*=2;console.log("betTotal doubled for Split");player_split_hand[0]=player_hand[1];player_hand[1]=deck.dealCard();player_split_hand[1]=deck.dealCard();splitCurrentHand=1;gameState='split';}else{alert("Not enough gratii bro");}}else{alert("Your cards must match to split.");}}
function clearTable(){player_split_hand=new Array();betTotal=0;previousBet=0;cardShowState=false;gameState='bet';winnerState='none';}
function quitGame(){exitGame();}
function help(){alert("Try to get 21.");}
function gameplayButton(X,Y,WIDTH,HEIGHT,TEXT,TEXTX,TEXTY){this.x=X;this.y=Y;this.width=WIDTH;this.height=HEIGHT;this.text=TEXT;this.textx=TEXTX;this.texty=TEXTY;this.textcolor="#777777";this.fontSize=16;this.clicked=function(clickx,clicky){if(checkButtonRectCollision(clickx,clicky,this.x,this.y,this.width,this.height)==true)
return true;};this.draw=function(){canvas.getContext("2d").drawImage(buttonBackImage,this.x,this.y+12);draw.text(this.text,this.textx,this.texty-10,this.fontSize,this.textcolor);};this.showCollisionOutline=function(){ctx.globalAlpha=0.5;draw.rect(this.x,this.y,this.width,this.height,'red');ctx.globalAlpha=1;}}
function checkButtonRectCollision(clickX,clickY,x1,y1,width,height){var y2=y1+height;var x2=x1+width;if(clickX>x1&&clickX<x2&&clickY>y1&&clickY<y2){return true;}else{return false;}}
function clickButtons(clickX,clickY){if(splashScreen==true){if(instructionScreen==true){splashScreen=false;instructionScreen=false;}
if(checkButtonRectCollision(clickX,clickY,0,360,canvas.width,70)==true){instructionScreen=true;}else{splashScreen=false;instructionScreen=false;}}else if(splashScreen==false){if(checkButtonRectCollision(clickX,clickY,0,0,59,34)==true)
quitGame();if(checkButtonRectCollision(clickX,clickY,60,0,44,34)==true)
help();if(gameState=='bet'){if(dealButton.clicked(clickX,clickY)==true)
deal();}else if(gameState=='game_over'||gameState=='split_game_over'){if(clearButton.clicked(clickX,clickY)==true)
clearTable();if(rebetButton.clicked(clickX,clickY)==true)
reBet();}else if(gameState=='play'){if(hitButton.clicked(clickX,clickY)==true)
hit();if(standButton.clicked(clickX,clickY)==true)
stand();if(doubleButton.clicked(clickX,clickY)==true)
doubleUp();if(splitButton.clicked(clickX,clickY)==true)
split();}else if(gameState=='split'){if(splitHitButton.clicked(clickX,clickY)==true)
hit();if(splitStandButton.clicked(clickX,clickY)==true)
stand();}
if(gameState=='bet'){if(checkButtonRectCollision(clickX,clickY,firstBetButtonX,canvas.height-140,49,60)==true)
addBet(5);if(checkButtonRectCollision(clickX,clickY,firstBetButtonX+50,canvas.height-142,51,60)==true)
addBet(25);if(checkButtonRectCollision(clickX,clickY,firstBetButtonX+102,canvas.height-144,57,60)==true)
addBet(100);if(checkButtonRectCollision(clickX,clickY,112,canvas.height/2-72,iconsXValue()-60,80)==true)
clearBet(betTotal);}}}
function drawButtons(){var fontSize=16;if(gameState=='bet'){canvas.getContext("2d").drawImage(chipsImage,160,canvas.height-138);dealButton.draw();}else if(gameState=='game_over'||gameState=='split_game_over'){clearButton.draw();rebetButton.draw();}else if(gameState=='play'){hitButton.draw();standButton.draw();doubleButton.draw();splitButton.draw();}else if(gameState=='split'){splitHitButton.draw();splitStandButton.draw();}}
function drawCards(){if(gameState=='play'||gameState=='game_over'||gameState=='split'||gameState=='split_game_over'){for(var i=0;i<dealer_hand.length;i++){if(i==0&&gameState=='play'){canvas.getContext("2d").drawImage(cardback.image,120,50);}else if(i==0&&gameState=='split'){canvas.getContext("2d").drawImage(cardback.image,120,44);}else if(i==0&&gameState=='game_over'){canvas.getContext("2d").drawImage(dealer_hand[i].image,120+i*22,50+i*4);}else if(i==0&&gameState=='split_game_over'){canvas.getContext("2d").drawImage(dealer_hand[i].image,120+i*22,44+i*2);}
if(i!=0&&gameState=='play'){canvas.getContext("2d").drawImage(dealer_hand[i].image,120+i*22,50+i*4);}else if(i!=0&&gameState=='game_over'){canvas.getContext("2d").drawImage(dealer_hand[i].image,120+i*22,50+i*4);}else if(i!=0&&gameState=='split_game_over'){canvas.getContext("2d").drawImage(dealer_hand[i].image,120+i*22,44+i*2);}else if(i==1&&gameState=='split'){canvas.getContext("2d").drawImage(dealer_hand[i].image,120+i*22,44+i*2);}}
if(gameState!='split'&&gameState!='split_game_over'){for(var i=0;i<player_hand.length;i++){canvas.getContext("2d").drawImage(player_hand[i].image,120+i*22,225+i*4);}}else if(gameState=='split'||gameState=='split_game_over'){for(var i=0;i<player_hand.length;i++){canvas.getContext("2d").drawImage(player_hand[i].image,50+i*22,142+i*2);}
for(var i=0;i<player_split_hand.length;i++){canvas.getContext("2d").drawImage(player_split_hand[i].image,50+i*22,240+i*2);}
if(gameState=='split'){if(splitCurrentHand==1){canvas.getContext("2d").drawImage(arrowImage,4,164);}else if(splitCurrentHand==2){canvas.getContext("2d").drawImage(arrowImage,4,264);}}}}}
function drawScore(){if(gameState=='play'){if(score(dealer_hand)!=null&score(player_hand)!=null){dealerHandScore=(score(dealer_hand));playerHandScore=(score(player_hand));draw.text(playerHandScore,canvas.width/2-8,canvas.height-90,12,'#CCCCCC');}}else if(gameState=='game_over'){if(score(dealer_hand)!=null&score(player_hand)!=null){dealerHandScore=(score(dealer_hand));playerHandScore=(score(player_hand));draw.text('Dealer:'+dealerHandScore,25,canvas.height-290,12,'#CCCCCC');draw.text(playerHandScore,canvas.width/2-8,canvas.height-90,12,'#CCCCCC');}}else if(gameState=='split'){if(score(dealer_hand)!=null&score(player_hand)!=null){dealerHandScore=(score(dealer_hand));playerHandScore=(score(player_hand));playerSplitHandScore=(score(player_split_hand));draw.text(playerHandScore,18,224,12,'#CCCCCC');draw.text(playerSplitHandScore,18,314,12,'#CCCCCC');}}else if(gameState=='split_game_over'){if(score(dealer_hand)!=null&score(player_hand)!=null){dealerHandScore=(score(dealer_hand));playerHandScore=(score(player_hand));playerSplitHandScore=(score(player_split_hand));draw.text('Dealer:'+dealerHandScore,25,canvas.height-290,12,'#CCCCCC');draw.text(playerHandScore,18,224,12,'#CCCCCC');draw.text(playerSplitHandScore,18,314,12,'#CCCCCC');}}}
function drawStatusBar(){var myGratiiLeft=250;if(myGratii<10)
myGratiiLeft=272;if(myGratii>=10&&myGratii<100)
myGratiiLeft=261;if(myGratii>=100&&myGratii<1000)
myGratiiLeft=250;if(myGratii>=1000&&myGratii<10000)
myGratiiLeft=239;if(myGratii>=10000&&myGratii<100000)
myGratiiLeft=228;draw.text(myGratii,myGratiiLeft,24,16,'#FFFFFF');canvas.getContext("2d").drawImage(coinImage,288,5);var betIndicatorsLeft=105;var betIndicatorsDisplayLeft=198;draw.text('Current Bet:',betIndicatorsLeft,30,12,'#cbcbcb');draw.text(previousBet,betIndicatorsDisplayLeft,30,12,'#cbcbcb');var helpLeft=60;draw.line(helpLeft,0,helpLeft,34,1,'#444444');draw.text('?',helpLeft+14,18,18,'#f4e450');draw.text('Help',helpLeft+7,30,10,'#cbcbcb');var cashOutLeft=0;draw.text('X',cashOutLeft+24,18,18,'#f0603e');draw.text('Cash Out',cashOutLeft+5,30,10,'#cbcbcb');}
var deck=new Deck();deck.shuffle();var cardback=new CardBack();var currentCard=0;var firstBetButtonX=160;var betTotal=0;var previousBet=0;var totalWon=0;var temporaryWon=0;var myGratii=0;getUserGratii();var gameState='bet';var winnerState='none';var cardShowState=false;var dealer_hand;var player_hand;var player_split_hand;var splitCurrentHand=0;var playerHandScore=0;var playerSplitHandScore=0;var dealerHandScore=0;var dealButton=new gameplayButton(120,canvas.height-75,78,74,"Deal",140,canvas.height-19);var hitButton=new gameplayButton(4,canvas.height-75,78,74,"Hit",31,canvas.height-19);var standButton=new gameplayButton(82,canvas.height-75,78,74,'Stand',97,canvas.height-19);var doubleButton=new gameplayButton(160,canvas.height-75,78,74,"Double",168,canvas.height-19);var splitButton=new gameplayButton(238,canvas.height-75,78,74,"Split",257,canvas.height-19);var clearButton=new gameplayButton(82,canvas.height-75,78,74,"Clear",97,canvas.height-19);var rebetButton=new gameplayButton(160,canvas.height-75,78,74,"Re-Bet",168,canvas.height-19);var splitHitButton=new gameplayButton(82,canvas.height-75,78,74,"Hit",108,canvas.height-19);var splitStandButton=new gameplayButton(160,canvas.height-75,78,74,"Stand",173,canvas.height-19);function iconsXValue(){var clearLeft=142;if(betTotal<10){clearLeft+=16;return clearLeft;}else if(betTotal<100){clearLeft+=16*2;return clearLeft;}else if(betTotal>=100&&betTotal<1000){clearLeft+=16*3;return clearLeft;}else if(betTotal>=1000&&betTotal<10000){clearLeft+=16*4;return clearLeft;}else if(betTotal>=10000&&betTotal<100000){clearLeft+=16*5;return clearLeft;}else if(betTotal>=100000){clearLeft+=16*6;return clearLeft;}}
function displayGameResults(){var resultX=110;var iconsX=iconsXValue();if(gameState!='split'&&gameState!='split_game_over'){if(winnerState=='player'){draw.text('+'+betTotal,resultX,canvas.height/2-20,24,'#02e807');canvas.getContext("2d").drawImage(gPlusImage,iconsX-10,canvas.height/2-40);}else if(winnerState=='dealer'){draw.text(' -'+betTotal,resultX,canvas.height/2-20,24,'#f0603e');canvas.getContext("2d").drawImage(gMinusImage,iconsX-10,canvas.height/2-40);}else if(winnerState=='tie'){draw.text('Push',resultX+4,canvas.height/2-20,24,'#CCCCCC');}else if(winnerState=='none'&&betTotal>0&&gameState!='split'){if(gameState=='bet'){ctx.globalAlpha=.6;draw.circle(iconsX+16,canvas.height/2-50,8,'#F4E450');ctx.globalAlpha=.8;draw.text('x',iconsX+13,canvas.height/2-45,12,'#cccccc');draw.text('x',iconsX+12,canvas.height/2-46,12,'#222222');ctx.globalAlpha=1;}
draw.text(betTotal,resultX+20,canvas.height/2-20,24,'#f4e450');canvas.getContext("2d").drawImage(gImage,iconsX-10,canvas.height/2-40);}else if(winnerState=='playerblackjack'){draw.text('+'+Math.round((3/2)*betTotal),resultX,canvas.height/2-20,24,'#02e807');canvas.getContext("2d").drawImage(gPlusImage,iconsX-10,canvas.height/2-40);}}else if(gameState=='split'){draw.text('Your Bet:'+betTotal,8,canvas.height/2-75,14,'#f4e450');}else if(gameState=='split_game_over'){if(temporaryWon<0){draw.text(temporaryWon,canvas.width-84,220,16,'#f0603e');}else if(temporaryWon==0){draw.text('Push',canvas.width-90,220,16,'#CCCCCC');}else if(temporaryWon>0){draw.text('+'+temporaryWon,canvas.width-90,220,16,'#02e807');}
if(winnerState=='player'){draw.text('+'+betTotal,canvas.width-90,310,16,'#02e807');}else if(winnerState=='dealer'){draw.text(' -'+betTotal/2,canvas.width-90,310,16,'#f0603e');}else if(winnerState=='tie'){draw.text('Push',canvas.width-90,310,16,'#CCCCCC');}}}
function splashLoop(){if(instructionScreen==true){canvas.getContext("2d").drawImage(instructionsImage,0,0);}else if(instructionScreen==false){canvas.getContext("2d").drawImage(splashImage,0,0);}}
function gameLoop(){if(splashScreen==true){splashLoop();}else if(splashScreen==false){draw.clear();if(cardShowState==true&&betTotal>0&&gameState=='deal'){newGame();gameState='play';}else if(cardShowState==true&&betTotal==0&&gameState=='bet'){cardShowState=false;alert("You must place a bet to play at this table bro");}
drawCards();drawButtons();drawStatusBar();drawScore();displayGameResults();checkIfBlackjack();}}
var loopInterval=setInterval(gameLoop,30);var startEvent='click';try{document.createEvent('TouchEvent');startEvent='touchstart';touchDevice=true;}catch(e){}
if(touchDevice==true){canvas.addEventListener(startEvent,touchHandler,true);function touchHandler(e){var touch={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY};clickButtons(touch.x,touch.y);}}
if(touchDevice==false){function clickHandler(e){var offsets=canvas.getBoundingClientRect();var click={x:e.clientX-offsets.left,y:e.clientY-offsets.top};clickButtons(click.x,click.y);}
canvas.addEventListener('click',clickHandler,true);}
console.log(touchDevice);}());